# Generated by Django 3.2.6 on 2021-08-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(default='no_picture_product.png', upload_to='drivers'),
        ),
    ]
