# Generated by Django 3.2.6 on 2021-08-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(default='1.png', upload_to='assets/img/cars'),
        ),
        migrations.AlterField(
            model_name='carownerdriverregister',
            name='image',
            field=models.ImageField(default='no_picture_product.png', upload_to='assets/img/drivers'),
        ),
    ]
