# Generated by Django 3.2.6 on 2021-08-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_car_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(default='1.png', upload_to='img/cars/'),
        ),
    ]
