# Generated by Django 3.2.6 on 2021-08-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_alter_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carownerdriverregister',
            name='image',
            field=models.ImageField(blank=True, default='car.png', upload_to=''),
        ),
    ]
