# Generated by Django 3.2.6 on 2021-08-25 09:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_alter_carownerdriverregister_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='carownerdriverregister',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carownerdriverregister',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='carbrand',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
