# Generated by Django 3.2.6 on 2021-08-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_auto_20210825_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='carownerdriverregister',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
