# Generated by Django 3.2.6 on 2021-08-25 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_auto_20210825_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carownerdriverregister',
            name='created_by',
        ),
    ]
