# Generated by Django 3.2.6 on 2021-08-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0015_remove_carownerdriverregister_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='carownerdriverregister',
            name='marital_status',
            field=models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced')], default='married', max_length=10),
            preserve_default=False,
        ),
    ]
