# Generated by Django 3.2.6 on 2021-08-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0016_carownerdriverregister_marital_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carownerdriverregister',
            name='nationality',
            field=models.CharField(choices=[('nigeria', 'Nigeria')], default='Nigeria', max_length=20),
        ),
        migrations.AlterField(
            model_name='carownerdriverregister',
            name='state_of_origin',
            field=models.CharField(choices=[('lagos', 'Lagos'), ('nasarawa', 'Nasarawa'), ('abia', 'Abia'), ('adamawa', 'Adamawa'), ('anambra', 'Anambra'), ('akwa-ibom', 'Akwa-Ibom'), ('delta', 'Delta'), ('edo', 'Edo'), ('enugu', 'Enugu'), ('jigawa', 'Jigawa'), ('ondo', 'Ondo'), ('imo', 'Imo'), ('bauchi', 'Bauchi'), ('plateau', 'Plateau'), ('ogun', 'Ogun'), ('kaduna', 'Kaduna'), ('katsina', 'Katsina'), ('sokoto', 'Sokoto'), ('osun', 'Osun'), ('benue', 'Benue'), ('kogi', 'Kogi'), ('fct(Abuja)', 'FCT(Abuja)'), ('ebonyi', 'Ebonyi'), ('cross-rivers', 'Cross-Rivers')], max_length=15),
        ),
        migrations.AlterField(
            model_name='carownerdriverregister',
            name='state_of_residence',
            field=models.CharField(choices=[('lagos', 'Lagos'), ('nasarawa', 'Nasarawa'), ('abia', 'Abia'), ('adamawa', 'Adamawa'), ('anambra', 'Anambra'), ('akwa-ibom', 'Akwa-Ibom'), ('delta', 'Delta'), ('edo', 'Edo'), ('enugu', 'Enugu'), ('jigawa', 'Jigawa'), ('ondo', 'Ondo'), ('imo', 'Imo'), ('bauchi', 'Bauchi'), ('plateau', 'Plateau'), ('ogun', 'Ogun'), ('kaduna', 'Kaduna'), ('katsina', 'Katsina'), ('sokoto', 'Sokoto'), ('osun', 'Osun'), ('benue', 'Benue'), ('kogi', 'Kogi'), ('fct(Abuja)', 'FCT(Abuja)'), ('ebonyi', 'Ebonyi'), ('cross-rivers', 'Cross-Rivers')], default='fct(Abuja)', max_length=50),
        ),
    ]
