# Generated by Django 3.2.6 on 2021-08-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0017_auto_20210825_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, default='1.png', null=True, upload_to='image/'),
        ),
    ]
