# Generated by Django 3.2.6 on 2021-08-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('1', 'pending'), ('2', 'active'), ('3', 'done')], default=1, max_length=1),
        ),
    ]
