# Generated by Django 3.2.6 on 2021-08-20 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_auto_20210820_0920'),
        ('riders', '0003_auto_20210820_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='service_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.rideserviceclass'),
        ),
    ]
