# Generated by Django 3.2.6 on 2021-08-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0004_ride_service_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='car',
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('1', 'pending'), ('2', 'arriving'), ('3', 'active'), ('4', 'done')], default=1, max_length=1),
        ),
    ]
