# Generated by Django 3.2.6 on 2021-08-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0007_alter_ride_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='destination',
            field=models.CharField(max_length=255),
        ),
    ]
