# Generated by Django 3.2.6 on 2021-08-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0010_alter_ride_pickup_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='pickup_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
